// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQwsNPTZVx6seaK1hw1RybeAxI1jREuuA',
    appId: '1:145066610418:web:02fc12b74b3e93ca7d0a6b',
    messagingSenderId: '145066610418',
    projectId: 'educonnect-final-de908',
    authDomain: 'educonnect-final-de908.firebaseapp.com',
    storageBucket: 'educonnect-final-de908.firebasestorage.app',
    measurementId: 'G-G4M8CCMTVZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP1a4Xw5GhfUeMoqu-oKUKsKOTovYW-kQ',
    appId: '1:145066610418:android:2120b5118ce8a5d07d0a6b',
    messagingSenderId: '145066610418',
    projectId: 'educonnect-final-de908',
    storageBucket: 'educonnect-final-de908.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALJI9KYCXMu-vkR3GKK0iPd8_kbpsXYK4',
    appId: '1:145066610418:ios:39cab667aabb56377d0a6b',
    messagingSenderId: '145066610418',
    projectId: 'educonnect-final-de908',
    storageBucket: 'educonnect-final-de908.firebasestorage.app',
    iosBundleId: 'com.example.educonnectFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALJI9KYCXMu-vkR3GKK0iPd8_kbpsXYK4',
    appId: '1:145066610418:ios:39cab667aabb56377d0a6b',
    messagingSenderId: '145066610418',
    projectId: 'educonnect-final-de908',
    storageBucket: 'educonnect-final-de908.firebasestorage.app',
    iosBundleId: 'com.example.educonnectFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQwsNPTZVx6seaK1hw1RybeAxI1jREuuA',
    appId: '1:145066610418:web:2a36543b07c589067d0a6b',
    messagingSenderId: '145066610418',
    projectId: 'educonnect-final-de908',
    authDomain: 'educonnect-final-de908.firebaseapp.com',
    storageBucket: 'educonnect-final-de908.firebasestorage.app',
    measurementId: 'G-MXZJNTX51E',
  );
}
